language: node_js
node_js: node
deploy:
  provider: npm
  email: core@donejs.com
  api_key:
    secure: Szd4jlzCjvZQ+BbN3kOQ2HB8UwMqoc0e9fW6kKeXAXRiD+ncQP/xAgYVhVtlIhCfGcX/u1m7MvMdU75izciFEZnAskmcL1IdUCHKgePmhbiUQF7FHeFUt8tDWnArUK9cdRqPrx/96guQFiqAZU3lk+JomxVoFQct449akPXzpS64x8TaenVMTdD0bzFwur+nhf8J5+Ohdho034xivS6f9zhJ4QKkdkAWWqAl5fHYOtGP1UDIlzvI2abnk5d+uXuFguCPAADeU+/Cuolvz4YDby1Fefe/z4K4nk81qBv6hv1z+owx//JVOb9cn1ClNItfY0qtQc1mafMxKSu/CYvSUQaLbT+3MUxN3++xPZxJwem6pI7iMSFI/nUyIuAvrVEXy7xm0jdo3T8gQpMOK1lywtBhXbdggwxJ4CXTkJqUKkU7SaivQrB4XNKvstoA8canGNQBuMpa8VUddfgZrwwiSwrDU6KTMGz2GiymfNUyKEdu6Ayl1xsPcyWRB8H7mqi4fhTEqZHsTlv6nJQ3u2sMsqOGbmolvHGhJIKn1kpU16zE68sZkkNV336ZBZm9uAl+RN+EIJxraHWf+chEuL1Rkj9wDPy9V7X+QHwgkGExPFiIIWJwEuSUbuUmVvvns/iqxzmexgCdqrOYCZgsGLNSBcvn80PWKpTs2wvadDykYOU=
  on:
    tags: true
    repo: bitovi/grunt-testee

dist: focal
services:
  - xvfb
