language: node_js
node_js: node
deploy:
  provider: npm
  email: core@donejs.com
  api_key:
    secure: WvOmXe61zx/qkYWPE9DK/lk+kdLDhrwnWLqUhQtr64BBqjQloNd5LouQ6TXkfa+h6zFp9n0W24e2VDZ0lnMaIA23dB/dFv+d3qodoJrwFBQ/U/fEoVTnT63VN6jmRwTXr5Mq94kzvB/9A2QjOc/nR5+aGeAA9qaVNC/JZsPpoxDn4ES/kRJNRvQNrBd0jQvvnKgzWk8R2H2H5Z6vci8SR1t+bmqfQYa1CUTFgLI7DwDETOB08YfskEXYLEjYUB2WUG1zY5NUWWIGMVEI5Xtj3yHf4D7SyeSN2REOXX0tfYki3t9wkxL3pyPbiLCBQvfsWtLZPmnYO6X+voHgDGN39zSSVwdeXwwMwOflxXnM1zCqvp9nz3A6duo22Snl1zO/0YcGH+Xaodyhq51EL2fe/UbFQ09lwPkPJWlS9ruovHD6GBYhFSYn5TW4jNT3dyWRnBKw6wADbC+RbGqhCJh5tOXBAV9iVRt9UkUeouR1pN8hDmsKkQpvknfbNZynK45cjS/QtiyMBjzqf1fDRrDCynRdtvgk023jNbqTmZSHLC2XIYd3Vzo+GSNAkIO2qfj3tG/HMsK8vh26opE9NI51jI2m5WQt54XPfbVw9snbF8sbIZ5fxt+FfBLBUY2RzbiZtSooQ0O0OSFzPITAy4RkB01rrZiJhcpy1H0mBjOpf6w=
  on:
    tags: true
    repo: bitovi/grunt-testee
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
addons:
  firefox: '51.0'
